server:
  port: 9191
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ericatsu29@gmail.com
    password: emailPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true