server:
  port: 9191
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
